layout(local_size_x = merge_bounding_box_contact_detectors_local_size) in;
void main()
{
	uint index = gl_GlobalInvocationID.x;
	uint count = fixed_data.read_counts[bounding_box_contact_detector_type];
	if (index >= count)
	{
		return;
	}

	uint indices_source_flags_base = fixed_data.bounding_box_contact_detector_indices_source_flags_base;

	uint indices_source_flags_index = indices_source_flags_base + index;

	uvec4 indices_source_flags = uvec4_data.data[indices_source_flags_index];

	if (indices_source_flags.w == 0u)
	{	// This detector is not willing to merge any side (typical case).
		return;
	}

	uint bounding_box_parent_children_height_base = fixed_data.inner_bounding_box_parent_children_height_base;
	uint lookup_table_base = fixed_data.mergeable_bounding_box_contact_detector_lookup_table_base;

	uint unmerged_side = indices_source_flags.w & bounding_box_contact_detector_willing_to_merge_side_0_mask;
	uint merged_side = indices_source_flags.w >> bounding_box_contact_detector_willing_to_merge_side_1_shift;

	uint unmerged_index = indices_source_flags[unmerged_side];
	uint merged_index = indices_source_flags[merged_side];

	uvec4 merged_side_parent_children_height = uvec4_data.data[bounding_box_parent_children_height_base + merged_index];
	uvec4 merged_to_parent_children_height = uvec4_data.data[bounding_box_parent_children_height_base + merged_side_parent_children_height.x];

	uint merged_to_parent_child_side = uint(merged_to_parent_children_height.z == merged_index);
	uint merged_to_parent_other_child_side = merged_to_parent_child_side ^ 1u;

	uint merged_to_parent_other_child_index = merged_to_parent_children_height[1u + merged_to_parent_other_child_side];

	uint lookup_table_capacity = fixed_data.mergeable_bounding_box_contact_detector_lookup_table_capacity;
	uint other_detector_lookup_index = compute_mergeable_contact_detector_lookup_index(unmerged_index, merged_to_parent_other_child_index, lookup_table_capacity);
	uint other_detector_index = uint_data.data[lookup_table_base + other_detector_lookup_index];

	while (other_detector_index != null_uint)
	{
		uvec4 other_indices_source_flags = uvec4_data.data[indices_source_flags_base + other_detector_index];

		if
		(
			other_indices_source_flags.w == 0u ||
			compute_mergeable_contact_detector_lookup_index(other_indices_source_flags.x, other_indices_source_flags.y, lookup_table_capacity) != other_detector_lookup_index
		)
		{
			break;
		}

		if
		(
			(other_indices_source_flags.x == unmerged_index && other_indices_source_flags.y == merged_to_parent_other_child_index) ||
			(other_indices_source_flags.x == merged_to_parent_other_child_index && other_indices_source_flags.y == unmerged_index)
		)
		{	// The matching detector also wants to merge.
			if (merged_to_parent_child_side == 1u)
			{
				kill(bounding_box_contact_detector_type, index);
			}
			else
			{
				indices_source_flags[merged_side] = merged_side_parent_children_height.x;
				uvec4_data.data[indices_source_flags_index] = indices_source_flags;
			}
			return;
		}

		other_detector_index = other_indices_source_flags.z;	// TODO: Rename source -> next.
	}
	// No matching detector found that was willing to merge.
}
