void convert_to_specific_detector
(
	in uint bounding_box_parent_children_height_base, in uint inner_bounding_box_base, in uint index, in uvec4 indices_source_flags
)
{
	uvec4 parent_pad_pad_type_0 = uvec4_data.data[bounding_box_parent_children_height_base + indices_source_flags.x];
	uvec4 parent_pad_pad_type_1 = uvec4_data.data[bounding_box_parent_children_height_base + indices_source_flags.y];

	uint contact_type = compute_contact_type(parent_pad_pad_type_0, parent_pad_pad_type_1);
	uint contact_detector_type = contact_detector_type_base + contact_type;
	uint specific_index = spawn(contact_detector_type);
	uint specific_capacity = fixed_data.capacities[contact_detector_type];
	if (specific_index >= specific_capacity)
	{
		undo_spawn(contact_detector_type);
		return;
	}

	uint leaf_bounding_box_base_0 = fixed_data.leaf_bounding_box_bases[parent_pad_pad_type_0.w];
	uint leaf_bounding_box_base_1 = fixed_data.leaf_bounding_box_bases[parent_pad_pad_type_1.w];
	uint specific_indices_base = fixed_data.specific_contact_detector_indices_bases[contact_type];
	uvec2_data.data[specific_indices_base + specific_index] = uvec2
	(
		inner_bounding_box_base + indices_source_flags.x - leaf_bounding_box_base_0,
		inner_bounding_box_base + indices_source_flags.y - leaf_bounding_box_base_1
	);

	kill(bounding_box_contact_detector_type, index);
}

const uint shared_cache_capacity = 1u;	// Both caches do not necessarily have to share this capacity.
const uint stack_cache_capacity = shared_cache_capacity;	// Must be >= 1u.
const uint flush_cache_capacity = shared_cache_capacity;	// Must be >= 1u.

void flush
(
	in uint indices_source_flags_base,
	in uint base,
	in uvec2 cached_flush_indices[flush_cache_capacity],
	in uint cached_flush_size
)
{
	uint global_base = indices_source_flags_base + base;
	for (uint i = 0u; i < cached_flush_size; ++i)
	{
		uvec4_data.data[global_base + i] = uvec4(cached_flush_indices[i], null_uint, 0u);
	}
}

void split_recursively
(
	in uint indices_source_flags_base,
	in uint bounding_box_parent_children_height_base,
	in uint bounding_box_base,
	in uint capacity,
	in uint index,
	in uvec4 indices_source_flags,
	in ivec4 bounding_boxes[2u]
)
{
	uint original_index = index;

	uvec2 cached_stack_indices[stack_cache_capacity];
	ivec4 cached_stack_bounding_boxes[stack_cache_capacity][2u];

	cached_stack_indices[0u] = indices_source_flags.xy;
	cached_stack_bounding_boxes[0u][0u] = bounding_boxes[0u];
	cached_stack_bounding_boxes[0u][1u] = bounding_boxes[1u];

	uint stack_size = 1u;

	uvec2 cached_flush_indices[flush_cache_capacity];
	uint cached_flush_size = 0u;

	do
	{
		uvec2 indices;
		uint source = 0u;
		ivec4 bounding_boxes[2u];

		// Pop
		--stack_size;
		if (stack_size < stack_cache_capacity)
		{	// Typical case.
			indices = cached_stack_indices[stack_size];
			bounding_boxes[0u] = cached_stack_bounding_boxes[stack_size][0u];
			bounding_boxes[1u] = cached_stack_bounding_boxes[stack_size][1u];
		}
		else
		{	// Fallback if cache capacity is insufficient (unlikely).
			indices_source_flags = uvec4_data.data[indices_source_flags_base + index];
			indices = indices_source_flags.xy;
			source = indices_source_flags.z;
			bounding_boxes[0u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.x]);
			bounding_boxes[1u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.y]);
		}

		if (bounding_boxes_are_separated(bounding_boxes))
		{	// Backtrack.
			if (stack_size == 0u)
			{
				uvec4_data.data[indices_source_flags_base + original_index] = uvec4(indices, null_uint, 0u);
				break;
			}

			if (stack_size < stack_cache_capacity)
			{	// Add the detector to the flush cache.
				if (cached_flush_size == flush_cache_capacity)
				{	// Fallback flush if cache capacity is insufficient (unlikely).
					uint base = spawn(bounding_box_contact_detector_type, cached_flush_size);
					if (base + cached_flush_size >= capacity)
					{	// MUST TODO: Retry logic.
						break;
					}
					flush(indices_source_flags_base, base, cached_flush_indices, cached_flush_size);
					cached_flush_size = 0u;
				}
				cached_flush_indices[cached_flush_size++] = indices;
			}

			index = source;	// Only well-defined if we are not inside the cache, which is intentional.
			continue;
		}

		bvec2 is_inner = bvec2
		(
			int(indices.x) >= 0,
			int(indices.y) >= 0
		);

		if (any(is_inner))
		{	// Split.
			uint costs[2u] = uint[2u]
			(
				uint(compute_bounding_box_cost(bounding_boxes[0u])),
				uint(compute_bounding_box_cost(bounding_boxes[1u]))
			);

			uint split_side = uint((costs[1u] > costs[0u] || (costs[1u] == costs[0u] && indices[1u] > indices[0u])) && is_inner[1u]);
			uint unsplit_side = split_side ^ 1u;

			uint split_index = indices[split_side];
			uint unsplit_index = indices[unsplit_side];

			uvec4 split_side_parent_children_height = uvec4_data.data[bounding_box_parent_children_height_base + split_index];

			// Give one child to the current detector.
			if (stack_size < stack_cache_capacity)
			{	// Typical case.
				cached_stack_indices[stack_size][split_side] = split_side_parent_children_height[1u];
				cached_stack_bounding_boxes[stack_size][split_side] = ivec4(uvec4_data.data[bounding_box_base + split_side_parent_children_height[1u]]);
			}
			else
			{	// Fallback if cache capacity is insufficient (unlikely).
				indices[split_side] = split_side_parent_children_height[1u];
				uvec4_data.data[indices_source_flags_base + index] = uvec4(indices, source, 0u);
			}
			++stack_size;
			
			// Give the other child to a new detector.
			if (stack_size < stack_cache_capacity)
			{	// Typical case.
				cached_stack_indices[stack_size] = uvec2(unsplit_index, split_side_parent_children_height[2u]);
				cached_stack_bounding_boxes[stack_size][0u] = bounding_boxes[unsplit_side];
				cached_stack_bounding_boxes[stack_size][1u] = ivec4(uvec4_data.data[bounding_box_base + split_side_parent_children_height[2u]]);
			}
			else
			{	// Fallback if cache capacity is insufficient (unlikely).
				uint new_index = spawn(bounding_box_contact_detector_type);
				if (new_index >= capacity)
				{	// MUST TODO: Retry logic.
					break;
				}
				uvec4_data.data[indices_source_flags_base + new_index] = uvec4(unsplit_index, split_side_parent_children_height[2u], index, 0u);
				index = new_index;
			}
			++stack_size;
		}
		else
		{
			convert_to_specific_detector(bounding_box_parent_children_height_base, bounding_box_base, index, indices_source_flags);
			if (stack_size == 0u)
			{
				break;
			}
			index = source;	// Only well-defined if we are not inside the cache, which is intentional.
		}
	} while (true);

	// Flush generated detectors to global memory.
	// IMPORTANT TODO: Consider reducing global memory atomic contention through shared memory atomics.
	uint base = spawn(bounding_box_contact_detector_type, cached_flush_size);
	if (base + cached_flush_size > capacity)
	{	// MUST TODO: Retry logic.
		return;
	}
	flush(indices_source_flags_base, base, cached_flush_indices, cached_flush_size);
}

// TODO: REMOVE.
void OLD_split_recursively
(
	in uint indices_source_flags_base,
	in uint bounding_box_parent_children_height_base,
	in uint bounding_box_base,
	in uint capacity,
	in uint index,
	in uvec4 indices_source_flags,
	in ivec4 bounding_boxes[2u]
)
{
	bvec2 is_inner = bvec2
	(
		int(indices_source_flags.x) >= 0,
		int(indices_source_flags.y) >= 0
	);
	if (any(is_inner))
	{
		uint detector_index = index;

		while (true)
		{	// Split logic.

			// Determine which box to split.
			uint cost_0 = compute_bounding_box_cost(bounding_boxes[0u]);
			uint cost_1 = compute_bounding_box_cost(bounding_boxes[1u]);
		
			uint split_side = uint((cost_1 > cost_0 || (cost_0 == cost_1 && indices_source_flags.y > indices_source_flags.x)) && is_inner.y);
			uint unsplit_side = split_side ^ 1u;
			
			uint split_index = indices_source_flags[split_side];
			uint unsplit_index = indices_source_flags[unsplit_side];
			
			uvec4 split_parent_children_height = uvec4_data.data[bounding_box_parent_children_height_base + split_index];
		
			// Update current detector -> one child.
			indices_source_flags[split_side] = split_parent_children_height.y;
			uvec4_data.data[indices_source_flags_base + detector_index] = indices_source_flags;	// TODO: Use index variable as detector_index.

			// Create new detector -> other child.
			uint new_detector_index = atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], 1u);
			if (new_detector_index >= capacity)	// MUST TODO: Retry shader logic.
			{
				atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], minus_1_uint);
				return;
			}

			indices_source_flags = uvec4(split_parent_children_height.z, unsplit_index, detector_index, 0u);
			uvec4_data.data[indices_source_flags_base + new_detector_index] = indices_source_flags;

			// IMPORTANT TODO: One of these fetches is redundant.
			bounding_boxes[0u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.x]);
			bounding_boxes[1u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.y]);

			is_inner[0u] = (int(indices_source_flags.x) >= 0);
			is_inner[1u] = (int(indices_source_flags.y) >= 0);

			detector_index = new_detector_index;

			if (bounding_boxes_overlap(bounding_boxes))
			{
				if (any(is_inner))
				{
					continue;	// Split the new detector as well.
				}
				else
				{
					convert_to_specific_detector(bounding_box_parent_children_height_base, bounding_box_base, detector_index, indices_source_flags);
				}
			}
			
			// IMPORTANT TODO: Avoid the need for backtracking by using next pointers instead of source pointers (ask ChatGPT).
			while (true)
			{	// Backtrack.
				uvec4_data.data[indices_source_flags_base + detector_index].z = null_uint;
				detector_index = indices_source_flags.z;	// Follow source pointer.
				
				indices_source_flags = uvec4_data.data[indices_source_flags_base + detector_index];

				bounding_boxes[0u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.x]);
				bounding_boxes[1u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.y]);
				
				is_inner[0u] = (int(indices_source_flags.x) >= 0);
				is_inner[1u] = (int(indices_source_flags.y) >= 0);

				if (bounding_boxes_overlap(bounding_boxes))
				{
					if (any(is_inner))
					{
						break;	// Resume splitting from this detector.
					}
					else
					{
						convert_to_specific_detector(bounding_box_parent_children_height_base, bounding_box_base, detector_index, indices_source_flags);
					}
				}
				if (detector_index == index)
				{
					return;
				}
			}
		}
	}
	else
	{
		convert_to_specific_detector(bounding_box_parent_children_height_base, bounding_box_base, index, indices_source_flags);	//  IMPORTANT TODO: Splitting logic.
	}
}

void tick_detector
(
	in uint index,
	in uint indices_source_flags_base,
	in uint bounding_box_base,
	in uint bounding_box_parent_children_height_base,
	in uint indices_source_flags_index,
	in uvec4 indices_source_flags
)
{
	uint bounding_box_index_0 = bounding_box_base + indices_source_flags.x;
	uint bounding_box_index_1 = bounding_box_base + indices_source_flags.y;

	ivec4 bounding_boxes[2u] = ivec4[2u]
	(
		ivec4(uvec4_data.data[bounding_box_index_0]),
		ivec4(uvec4_data.data[bounding_box_index_1])
	);

	if (bounding_boxes_overlap(bounding_boxes))
	{
		uint capacity = fixed_data.capacities[bounding_box_contact_detector_type];
		split_recursively
		(
			indices_source_flags_base,
			bounding_box_parent_children_height_base,
			bounding_box_base,
			capacity,
			index,
			indices_source_flags,
			bounding_boxes
		);

		/*bvec2 is_inner = bvec2
		(
			int(indices_source_flags.x) >= 0,
			int(indices_source_flags.y) >= 0
		);
		if (any(is_inner))
		{
			uint detector_index = index;
			uint detector_capacity = fixed_data.capacities[bounding_box_contact_detector_type];

			while (true)
			{	// Split logic.

				// Determine which box to split.
				uint cost_0 = compute_bounding_box_cost(bounding_boxes[0u]);
				uint cost_1 = compute_bounding_box_cost(bounding_boxes[1u]);
		
				uint split_side = uint(cost_1 > cost_0 && is_inner.y);
				uint unsplit_side = split_side ^ 1u;
			
				uint split_index = indices_source_flags[split_side];
				uint unsplit_index = indices_source_flags[unsplit_side];
			
				uvec4 split_parent_children_height = uvec4_data.data[bounding_box_parent_children_height_base + split_index];
		
				// Update current detector -> one child.
				indices_source_flags[split_side] = split_parent_children_height.y;
				uvec4_data.data[indices_source_flags_base + detector_index] = indices_source_flags;	// TODO: Use index variable as detector_index.

				// Create new detector -> other child.
				uint new_detector_index = atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], 1u);
				if (new_detector_index >= detector_capacity)	// MUST TODO: Retry shader logic.
				{
					atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], minus_1_uint);
					return;
				}

				indices_source_flags = uvec4(split_parent_children_height.z, unsplit_index, detector_index, 0u);
				uvec4_data.data[indices_source_flags_base + new_detector_index] = indices_source_flags;

				// IMPORTANT TODO: One of these fetches is redundant.
				bounding_boxes[0u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.x]);
				bounding_boxes[1u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.y]);

				is_inner[0u] = (int(indices_source_flags.x) >= 0);
				is_inner[1u] = (int(indices_source_flags.y) >= 0);

				detector_index = new_detector_index;

				if (bounding_boxes_overlap(bounding_boxes))
				{
					if (any(is_inner))
					{
						continue;	// Split the new detector as well.
					}
					else
					{
						convert_to_specific_detector(bounding_box_parent_children_height_base, bounding_box_base, detector_index, indices_source_flags);
					}
				}
			
				// IMPORTANT TODO: Avoid the need for backtracking by using next pointers instead of source pointers (ask ChatGPT).
				while (true)
				{	// Backtrack.
					uvec4_data.data[indices_source_flags_base + detector_index].z = null_uint;
					detector_index = indices_source_flags.z;	// Follow source pointer.
				
					indices_source_flags = uvec4_data.data[indices_source_flags_base + detector_index];

					bounding_boxes[0u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.x]);
					bounding_boxes[1u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_flags.y]);
				
					is_inner[0u] = (int(indices_source_flags.x) >= 0);
					is_inner[1u] = (int(indices_source_flags.y) >= 0);

					if (bounding_boxes_overlap(bounding_boxes))
					{
						if (any(is_inner))
						{
							break;	// Resume splitting from this detector.
						}
						else
						{
							convert_to_specific_detector(bounding_box_parent_children_height_base, bounding_box_base, detector_index, indices_source_flags);
						}
					}
					if (detector_index == index)
					{
						return;
					}
				}
			}
		}
		else
		{
			convert_to_specific_detector(bounding_box_parent_children_height_base, bounding_box_base, index, indices_source_flags);	//  IMPORTANT TODO: Splitting logic.
		}*/
	}
	else
	{	// Merge logic.
		uvec4 parent_children_heights[2u] = uvec4[2u]
		(
			uvec4_data.data[bounding_box_parent_children_height_base + indices_source_flags.x],
			uvec4_data.data[bounding_box_parent_children_height_base + indices_source_flags.y]
		);

		ivec4 parent_bounding_boxes[2u] = ivec4[2u]
		(
			ivec4(uvec4_data.data[bounding_box_base + parent_children_heights[0u].x]),
			ivec4(uvec4_data.data[bounding_box_base + parent_children_heights[1u].x])
		);

		#define ONLY_MERGE_TO_SMALLEST_PARENT 0

		#if ONLY_MERGE_TO_SMALLEST_PARENT
		
			uint cost_0 = compute_bounding_box_cost(parent_bounding_boxes[0u]);
			uint cost_1 = compute_bounding_box_cost(parent_bounding_boxes[1u]);
			
			uint merged_side = uint(cost_1 < cost_0 || (cost_1 == cost_0 && parent_children_heights[1u].x < parent_children_heights[0u].x));
			uint unmerged_side = merged_side ^ 1u;

			if (bounding_boxes_are_separated(parent_bounding_boxes[merged_side], bounding_boxes[unmerged_side]))
			{
				indices_source_flags.w |= 1u << merged_side;
		#else
		
			if (bounding_boxes_are_separated(parent_bounding_boxes[0u], bounding_boxes[1u]))
			{
				indices_source_flags.w |= bounding_box_contact_detector_willing_to_merge_side_0_mask;
			}
			if (bounding_boxes_are_separated(parent_bounding_boxes[1u], bounding_boxes[0u]))
			{
				indices_source_flags.w |= bounding_box_contact_detector_willing_to_merge_side_1_mask;
			}

			if (indices_source_flags.w != 0u)
			{
		#endif
				uint lookup_table_capacity = fixed_data.mergeable_bounding_box_contact_detector_lookup_table_capacity;
				uint lookup_index = compute_mergeable_contact_detector_lookup_index(indices_source_flags.x, indices_source_flags.y, lookup_table_capacity);
				uint lookup_table_base = fixed_data.mergeable_bounding_box_contact_detector_lookup_table_base;
				uint head_index = lookup_table_base + lookup_index;

				// Insert detector into lookup table.
				uint old_head;
				do
				{
					old_head = uint_data.data[head_index];
					indices_source_flags.z = old_head;
					uvec4_data.data[indices_source_flags_index] = indices_source_flags;
				} while (atomicCompSwap(uint_data.data[head_index], old_head, index) != old_head);
			}
	}
}

layout(local_size_x = tick_bounding_box_contact_detectors_local_size) in;
void main()
{
	uint index = gl_GlobalInvocationID.x;
	uint count = fixed_data.read_counts[bounding_box_contact_detector_type];
	if (index >= count)
	{
		return;
	}
	
	uint indices_source_flags_base = fixed_data.bounding_box_contact_detector_indices_source_flags_base;

	uint indices_source_flags_index = indices_source_flags_base + index;

	uvec4 indices_source_flags = uvec4_data.data[indices_source_flags_index];

	uint bounding_box_base = fixed_data.inner_bounding_box_base;
	uint bounding_box_parent_children_height_base = fixed_data.inner_bounding_box_parent_children_height_base;
	uint bounding_box_split_indices_base = fixed_data.inner_bounding_box_split_indices_base;
	uint bounding_box_moved_to_base = fixed_data.inner_bounding_box_moved_to_base;

	uint moved_to_0 = indices_source_flags.x;
	if (int(indices_source_flags.x) >= 0)	// IMPORTANT TODO: Store expression in variable.
	{
		moved_to_0 = uint_data.data[bounding_box_moved_to_base + indices_source_flags.x];
	}
	uint moved_to_1 = indices_source_flags.y;
	if (int(indices_source_flags.y) >= 0)
	{
		moved_to_1 = uint_data.data[bounding_box_moved_to_base + indices_source_flags.y];
	}
	if (any(bvec2(moved_to_0 != indices_source_flags.x, moved_to_1 != indices_source_flags.y)))
	{
		indices_source_flags.x = moved_to_0;
		indices_source_flags.y = moved_to_1;
		uvec4_data.data[indices_source_flags_index] = indices_source_flags;
	}

	// Initially assume that neither box was split, which is the typical case.
	uint detector_count = 1u;

	uint index_array[4u];
	index_array[0u] = index;
	
	uint indices_source_flags_index_array[4u];	// IMPORTANT TODO: Consider not storing this, and instead computing such indices on demand.
	indices_source_flags_index_array[0u] = indices_source_flags_index;
	
	uvec4 indices_source_flags_array[4u];
	indices_source_flags_array[0u] = indices_source_flags;

	bvec2 is_split = bvec2(false, false);
	uvec2 split_indices_array[2u];

	if (int(indices_source_flags.x) >= 0)
	{
		split_indices_array[0u] = uvec2_data.data[bounding_box_split_indices_base + indices_source_flags.x];
		is_split[0u] = (split_indices_array[0u].x != null_uint);
	}
	if (int(indices_source_flags.y) >= 0)
	{
		split_indices_array[1u] = uvec2_data.data[bounding_box_split_indices_base + indices_source_flags.y];
		is_split[1u] = (split_indices_array[1u].x != null_uint);
	}

	if (all(is_split))
	{	// Case whose probability approaches zero as the time step size approaches zero.
		uint second_index = atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], 3u);
		uint third_index = second_index + 1u;
		uint fourth_index = second_index + 2u;
		if (fourth_index >= fixed_data.capacities[bounding_box_contact_detector_type])
		{
			// MUST TODO: Increase capacity and retry shader.
			atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], minus_3_uint);
			return;
		}

		detector_count = 4u;

		indices_source_flags.x = split_indices_array[0u].x;
		indices_source_flags.y = split_indices_array[1u].x;
		indices_source_flags_array[0u] = indices_source_flags;
		uvec4_data.data[indices_source_flags_index] = indices_source_flags;

		index_array[1u] = second_index;
		uint second_indices_source_flags_index = indices_source_flags_base + second_index;
		indices_source_flags_index_array[1u] = second_indices_source_flags_index;
		uvec4 second_indices_source_flags = uvec4(split_indices_array[0u].x, split_indices_array[1u].y, null_uint, 0u);
		indices_source_flags_array[1u] = second_indices_source_flags;
		uvec4_data.data[second_indices_source_flags_index] = second_indices_source_flags;

		index_array[2u] = third_index;
		uint third_indices_source_flags_index = indices_source_flags_base + third_index;
		indices_source_flags_index_array[2u] = third_indices_source_flags_index;
		uvec4 third_indices_source_flags = uvec4(split_indices_array[0u].y, split_indices_array[1u].x, null_uint, 0u);
		indices_source_flags_array[2u] = third_indices_source_flags;
		uvec4_data.data[third_indices_source_flags_index] = third_indices_source_flags;

		index_array[3u] = fourth_index;
		uint fourth_indices_source_flags_index = indices_source_flags_base + fourth_index;
		indices_source_flags_index_array[3u] = fourth_indices_source_flags_index;
		uvec4 fourth_indices_source_flags = uvec4(split_indices_array[0u].y, split_indices_array[1u].y, null_uint, 0u);
		indices_source_flags_array[3u] = fourth_indices_source_flags;
		uvec4_data.data[fourth_indices_source_flags_index] = fourth_indices_source_flags;
	}
	else if (any(is_split))
	{	// Atypical case.
		uint second_index = atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], 1u);
		if (second_index >= fixed_data.capacities[bounding_box_contact_detector_type])
		{
			// MUST TODO: Increase capacity and retry shader.
			atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], minus_1_uint);
			return;
		}
		 
		uint split_side = uint(is_split[1u]);
		uint unsplit_side = split_side ^ 1u;
		uvec2 split_indices = split_indices_array[split_side];
		detector_count = 2u;

		indices_source_flags[split_side] = split_indices.x;
		indices_source_flags_array[0u] = indices_source_flags;
		uvec4_data.data[indices_source_flags_index] = indices_source_flags;

		index_array[1u] = second_index;
		uint second_indices_source_flags_index = indices_source_flags_base + second_index;
		indices_source_flags_index_array[1u] = second_indices_source_flags_index;
		uvec4 second_indices_source_flags = uvec4(split_indices.y, indices_source_flags[unsplit_side], null_uint, 0u);
		indices_source_flags_array[1u] = second_indices_source_flags;
		uvec4_data.data[second_indices_source_flags_index] = second_indices_source_flags;
	}

	for (uint detector = 0u; detector < detector_count; ++detector)
	{
		tick_detector
		(
			index_array[detector],
			indices_source_flags_base,
			bounding_box_base,
			bounding_box_parent_children_height_base,
			indices_source_flags_index_array[detector],
			indices_source_flags_array[detector]
		);
	}
}
