bool bounding_boxes_overlap(in ivec4 bounding_boxes[2u])
{
	return
	(
		all(lessThanEqual(bounding_boxes[0u].xy, bounding_boxes[1u].zw)) &&
		all(lessThanEqual(bounding_boxes[1u].xy, bounding_boxes[0u].zw))
	);
}

bool bounding_boxes_overlap(in ivec4 bounding_box_0, in ivec4 bounding_box_1)
{
	return
	(
		all(lessThanEqual(bounding_box_0.xy, bounding_box_1.zw)) &&
		all(lessThanEqual(bounding_box_1.xy, bounding_box_0.zw))
	);
}

bool bounding_boxes_are_separated(in ivec4 bounding_box_0, in ivec4 bounding_box_1)
{
	return
	(
		any(greaterThan(bounding_box_0.xy, bounding_box_1.zw)) ||
		any(greaterThan(bounding_box_1.xy, bounding_box_0.zw))
	);
}

void tick_detector
(
	in uint index,
	in uint indices_source_pad_base,
	in uint bounding_box_base,
	in uint bounding_box_parent_children_height_base,
	in uint indices_source_pad_index,
	in uvec4 indices_source_pad
)
{
	uint bounding_box_index_0 = bounding_box_base + indices_source_pad.x;
	uint bounding_box_index_1 = bounding_box_base + indices_source_pad.y;

	ivec4 bounding_boxes[2u] = ivec4[2u]
	(
		ivec4(uvec4_data.data[bounding_box_index_0]),
		ivec4(uvec4_data.data[bounding_box_index_1])
	);

	if (bounding_boxes_overlap(bounding_boxes))
	{
		bvec2 is_inner = bvec2
		(
			int(indices_source_pad.x) >= 0,
			int(indices_source_pad.y) >= 0
		);
		if (any(is_inner))
		{
			uint detector_index = index;
			uint detector_capacity = fixed_data.capacities[bounding_box_contact_detector_type];

			while (true)
			{	// Split logic.

				// Determine which box to split.
				uint cost_0 = compute_bounding_box_cost(bounding_boxes[0u]);
				uint cost_1 = compute_bounding_box_cost(bounding_boxes[1u]);
		
				uint split_side = uint(cost_1 > cost_0 && is_inner.y);
				uint unsplit_side = split_side ^ 1u;
			
				uint split_index = indices_source_pad[split_side];
				uint unsplit_index = indices_source_pad[unsplit_side];
			
				uvec4 split_parent_children_height = uvec4_data.data[bounding_box_parent_children_height_base + split_index];
		
				// Update current detector -> one child.
				indices_source_pad[split_side] = split_parent_children_height.y;
				uvec4_data.data[indices_source_pad_base + index] = indices_source_pad;

				// Create new detector -> other child.
				uint new_detector_index = atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], 1u);
				if (new_detector_index >= detector_capacity)
				{
					atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], minus_1_uint);
					return;
				}

				indices_source_pad = uvec4(split_parent_children_height.z, unsplit_index, detector_index, 0u);
				uvec4_data.data[indices_source_pad_base + new_detector_index] = indices_source_pad;

				bounding_boxes[0u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_pad.x]);
				bounding_boxes[1u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_pad.y]);

				detector_index = new_detector_index;

				if (bounding_boxes_overlap(bounding_boxes))
				{
					continue;	// Split the new detector as well.
				}
			
				// IMPORTANT TODO: Avoid the need for backtracking by using next pointers instead of source pointers (ask ChatGPT).
				while (true)
				{	// Backtrack.
				
					detector_index = indices_source_pad.z;	// Follow source pointer.
				
					indices_source_pad = uvec4_data.data[indices_source_pad_base + detector_index];
					bounding_boxes[0u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_pad.x]);
					bounding_boxes[1u] = ivec4(uvec4_data.data[bounding_box_base + indices_source_pad.y]);
				
					if (bounding_boxes_overlap(bounding_boxes))
					{
						break;	// Resume splitting from this detector.
					}
					if (detector_index == index)
					{
						return;
					}
				}
			}
		}
	}
	else
	{	// Collapse logic.
		uvec4 parent_children_heights[2u] = uvec4[2u]
		(
			uvec4_data.data[bounding_box_parent_children_height_base + indices_source_pad.x],
			uvec4_data.data[bounding_box_parent_children_height_base + indices_source_pad.y]
		);

		ivec4 parent_bounding_boxes[2u] = ivec4[2u]
		(
			ivec4(uvec4_data.data[bounding_box_base + parent_children_heights[0u].x]),
			ivec4(uvec4_data.data[bounding_box_base + parent_children_heights[1u].x])
		);

		uint collapse_cost = max_uint;
		uint collapse_side;
		if (bounding_boxes_are_separated(parent_bounding_boxes[0u], bounding_boxes[1u]))
		{
			collapse_cost = compute_bounding_box_cost(parent_bounding_boxes[0u]);
			collapse_side = 0u;
		}
		uint collapse_cost_1 = compute_bounding_box_cost(parent_bounding_boxes[1u]);
		if (bounding_boxes_are_separated(parent_bounding_boxes[1u], bounding_boxes[0u]) && collapse_cost_1 < collapse_cost)
		{
			collapse_cost = collapse_cost_1;
			collapse_side = 1u;
		}
		if (collapse_cost == max_uint)
		{
			return;
		}

		do
		{
			uvec4 collapse_parent_children_height = parent_children_heights[collapse_side];
			uvec4 collapse_parent_parent_children_height = uvec4_data.data[bounding_box_parent_children_height_base + collapse_parent_children_height.x];
			
			if (indices_source_pad[collapse_side] == collapse_parent_parent_children_height.z)	// Is the detector holding the right child of the collapsed node?
			{	// Die.
				kill(bounding_box_contact_detector_type, index);
				return;
			}
			
			// Perform collapse.
			indices_source_pad[collapse_side] = collapse_parent_children_height.x;
			bounding_boxes[collapse_side] = parent_bounding_boxes[collapse_side];
			parent_children_heights[collapse_side] = uvec4_data.data[bounding_box_parent_children_height_base + collapse_parent_children_height.x];
			parent_bounding_boxes[collapse_side] = ivec4(uvec4_data.data[bounding_box_base + parent_children_heights[collapse_side].x]);

			// Consider another collapse.
			collapse_cost = max_uint;
			if (bounding_boxes_are_separated(parent_bounding_boxes[0u], bounding_boxes[1u]))
			{
				collapse_cost = compute_bounding_box_cost(parent_bounding_boxes[0u]);
				collapse_side = 0u;
			}
			collapse_cost_1 = compute_bounding_box_cost(parent_bounding_boxes[1u]);
			if (bounding_boxes_are_separated(parent_bounding_boxes[1u], bounding_boxes[0u]) && collapse_cost_1 < collapse_cost)
			{
				collapse_cost = collapse_cost_1;
				collapse_side = 1u;
			}
		} while (collapse_cost != max_uint);

		uvec4_data.data[indices_source_pad_index] = indices_source_pad;
	}
}

layout(local_size_x = tick_bounding_box_contact_detectors_local_size) in;
void main()
{
	uint index = gl_GlobalInvocationID.x;
	uint count = fixed_data.read_counts[bounding_box_contact_detector_type];
	if (index >= count)
	{
		return;
	}
	
	uint indices_source_pad_base = fixed_data.bounding_box_contact_detector_indices_source_pad_base;

	uint indices_source_pad_index = indices_source_pad_base + index;

	uvec4 indices_source_pad = uvec4_data.data[indices_source_pad_index];

	uint bounding_box_base = fixed_data.inner_bounding_box_base;
	uint bounding_box_parent_children_height_base = fixed_data.inner_bounding_box_parent_children_height_base;
	uint bounding_box_split_indices_base = fixed_data.inner_bounding_box_split_indices_base;
	uint bounding_box_moved_to_base = fixed_data.inner_bounding_box_moved_to_base;

	uint moved_to_0 = indices_source_pad.x;
	if (int(indices_source_pad.x) >= 0)	// IMPORTANT TODO: Store expression in variable.
	{
		moved_to_0 = uint_data.data[bounding_box_moved_to_base + indices_source_pad.x];
	}
	uint moved_to_1 = indices_source_pad.y;
	if (int(indices_source_pad.y) >= 0)
	{
		moved_to_1 = uint_data.data[bounding_box_moved_to_base + indices_source_pad.y];
	}
	if (any(bvec2(moved_to_0 != indices_source_pad.x, moved_to_1 != indices_source_pad.y)))
	{
		indices_source_pad.x = moved_to_0;
		indices_source_pad.y = moved_to_1;
		uvec4_data.data[indices_source_pad_index] = indices_source_pad;
	}

	// Initially assume that neither box was split, which is the typical case.
	uint detector_count = 1u;

	uint index_array[4u];
	index_array[0u] = index;
	
	uint indices_source_pad_index_array[4u];	// IMPORTANT TODO: Consider not storing this, and instead computing such indices on demand.
	indices_source_pad_index_array[0u] = indices_source_pad_index;
	
	uvec4 indices_source_pad_array[4u];
	indices_source_pad_array[0u] = indices_source_pad;

	bvec2 is_split = bvec2(false, false);
	uvec2 split_indices_array[2u];

	if (int(indices_source_pad.x) >= 0)
	{
		split_indices_array[0u] = uvec2_data.data[bounding_box_split_indices_base + indices_source_pad.x];
		is_split[0u] = (split_indices_array[0u].x != null_uint);
	}
	if (int(indices_source_pad.y) >= 0)
	{
		split_indices_array[1u] = uvec2_data.data[bounding_box_split_indices_base + indices_source_pad.y];
		is_split[1u] = (split_indices_array[1u].x != null_uint);
	}

	if (all(is_split))
	{	// Case whose probability approaches zero as the time step size approaches zero.
		uint second_index = atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], 3u);
		uint third_index = second_index + 1u;
		uint fourth_index = second_index + 2u;
		if (fourth_index >= fixed_data.capacities[bounding_box_contact_detector_type])
		{
			// MUST TODO: Increase capacity and retry shader.
			atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], minus_3_uint);
			return;
		}

		detector_count = 4u;

		indices_source_pad.x = split_indices_array[0u].x;
		indices_source_pad.y = split_indices_array[1u].x;
		indices_source_pad_array[0u] = indices_source_pad;
		uvec4_data.data[indices_source_pad_index] = indices_source_pad;

		index_array[1u] = second_index;
		uint second_indices_source_pad_index = indices_source_pad_base + second_index;
		indices_source_pad_index_array[1u] = second_indices_source_pad_index;
		uvec4 second_indices_source_pad = uvec4(split_indices_array[0u].x, split_indices_array[1u].y, 0u, 0u);
		indices_source_pad_array[1u] = second_indices_source_pad;
		uvec4_data.data[second_indices_source_pad_index] = second_indices_source_pad;

		index_array[2u] = third_index;
		uint third_indices_source_pad_index = indices_source_pad_base + third_index;
		indices_source_pad_index_array[2u] = third_indices_source_pad_index;
		uvec4 third_indices_source_pad = uvec4(split_indices_array[0u].y, split_indices_array[1u].x, 0u, 0u);
		indices_source_pad_array[2u] = third_indices_source_pad;
		uvec4_data.data[third_indices_source_pad_index] = third_indices_source_pad;

		index_array[3u] = fourth_index;
		uint fourth_indices_source_pad_index = indices_source_pad_base + fourth_index;
		indices_source_pad_index_array[3u] = fourth_indices_source_pad_index;
		uvec4 fourth_indices_source_pad = uvec4(split_indices_array[0u].y, split_indices_array[1u].y, 0u, 0u);
		indices_source_pad_array[3u] = fourth_indices_source_pad;
		uvec4_data.data[fourth_indices_source_pad_index] = fourth_indices_source_pad;
	}
	else if (any(is_split))
	{	// Atypical case.
		uint second_index = atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], 1u);
		if (second_index >= fixed_data.capacities[bounding_box_contact_detector_type])
		{
			// MUST TODO: Increase capacity and retry shader.
			atomicAdd(fixed_data.write_counts[bounding_box_contact_detector_type], minus_1_uint);
			return;
		}
		 
		uint split_side = uint(is_split[1u]);
		uint unsplit_side = split_side ^ 1u;
		uvec2 split_indices = split_indices_array[split_side];
		detector_count = 2u;

		indices_source_pad[split_side] = split_indices.x;
		indices_source_pad_array[0u] = indices_source_pad;
		uvec4_data.data[indices_source_pad_index] = indices_source_pad;

		index_array[1u] = second_index;
		uint second_indices_source_pad_index = indices_source_pad_base + second_index;
		indices_source_pad_index_array[1u] = second_indices_source_pad_index;
		uvec4 second_indices_source_pad = uvec4(split_indices.y, indices_source_pad[unsplit_side], 0u, 0u);
		indices_source_pad_array[1u] = second_indices_source_pad;
		uvec4_data.data[second_indices_source_pad_index] = second_indices_source_pad;
	}

	for (uint detector = 0u; detector < detector_count; ++detector)
	{
		tick_detector
		(
			index_array[detector],
			indices_source_pad_base,
			bounding_box_base,
			bounding_box_parent_children_height_base,
			indices_source_pad_index_array[detector],
			indices_source_pad_array[detector]
		);
	}
}
