layout(local_size_x = 1u) in;
void main()
{
	fixed_data.temp_dispatch_command = uvec4(1u, 1u, 1u, 0u);

	fixed_data.temp = uint(-1);

	const uint distance = uint(int(0.5 * meter_in_length_units));
	uint rows = 10u;
	uint columns = 10u;

	const uint tick = uint(-1);
	fixed_data.tick = tick;

	fixed_data.camera_position = uvec4(0.0 * meter_in_length_units, 0.0 * meter_in_length_units, 5.0 * meter_in_length_units, 0u);
	uint camera_angle = 0u;
	mat4 camera_offset_to_local = mat4(1.0);
	
	fixed_data.camera_angle = camera_angle;
	fixed_data.camera_offset_to_local = camera_offset_to_local;

	vec2 projection = vec2(0.5, 1.0);
	mat4 camera_projection = mat4
	(
		projection.x, 0.0, 0.0, 0.0,
		0.0, projection.y, 0.0, 0.0,
		0.0, 0.0, 0.0, -1.0,
		0.0, 0.0, 0.0, 0.0
	);
	
	fixed_data.camera_offset_to_clip_coordinates = camera_projection * camera_offset_to_local;

	uint capacities[entity_type_count];

	uint old_death_index_base_addresses[entity_type_count];
	uint old_killed_base_addresses[entity_type_count];
	uint death_index_base_addresses[entity_type_count];
	uint killed_base_addresses[entity_type_count];

	uint old_death_index_bases[entity_type_count];
	uint old_killed_bases[entity_type_count];
	uint death_index_bases[entity_type_count];
	uint killed_bases[entity_type_count];

	capacities[point_mass_type_index] = rows * columns;

	uint point_mass_inverse_mass_base_address = align_up(fixed_data_buffer_data_size);
	uint point_mass_constraint_start_base_address = align_up(point_mass_inverse_mass_base_address + capacities[point_mass_type_index] * float_data_array_stride);
	uint point_mass_constraint_end_base_address = align_up(point_mass_constraint_start_base_address + capacities[point_mass_type_index] * uint_data_array_stride);
	uint point_mass_read_flags_base_address = align_up(point_mass_constraint_end_base_address + capacities[point_mass_type_index] * uint_data_array_stride);
	uint point_mass_read_position_velocity_base_address = align_up(point_mass_read_flags_base_address + capacities[point_mass_type_index] * uint_data_array_stride);
	uint point_mass_write_flags_base_address = align_up(point_mass_read_position_velocity_base_address + capacities[point_mass_type_index] * uvec4_data_array_stride);
	uint point_mass_write_position_velocity_base_address = align_up(point_mass_write_flags_base_address + capacities[point_mass_type_index] * uint_data_array_stride);

	uint point_mass_inverse_mass_base = address_to_float_index(point_mass_inverse_mass_base_address);
	uint point_mass_constraint_start_base = address_to_uint_index(point_mass_constraint_start_base_address);
	uint point_mass_constraint_end_base = address_to_uint_index(point_mass_constraint_end_base_address);
	uint point_mass_read_flags_base = address_to_uint_index(point_mass_read_flags_base_address);
	uint point_mass_read_position_velocity_base = address_to_uvec4_index(point_mass_read_position_velocity_base_address);
	uint point_mass_write_flags_base = address_to_uint_index(point_mass_write_flags_base_address);
	uint point_mass_write_position_velocity_base = address_to_uvec4_index(point_mass_write_position_velocity_base_address);

	fixed_data.point_mass_inverse_mass_base = point_mass_inverse_mass_base;
	fixed_data.point_mass_constraint_start_base = point_mass_constraint_start_base;
	fixed_data.point_mass_constraint_end_base = point_mass_constraint_end_base;
	fixed_data.point_mass_read_flags_base = point_mass_read_flags_base;
	fixed_data.point_mass_read_position_velocity_base = point_mass_read_position_velocity_base;
	fixed_data.point_mass_write_flags_base = point_mass_write_flags_base;
	fixed_data.point_mass_write_position_velocity_base = point_mass_write_position_velocity_base;
	
	capacities[rigid_body_type_index] = 100u;

	uint rigid_body_inverse_mass_inertia_base_address = align_up(point_mass_write_position_velocity_base_address + capacities[point_mass_type_index] * uvec4_data_array_stride);
	uint rigid_body_constraint_start_base_address = align_up(rigid_body_inverse_mass_inertia_base_address + capacities[rigid_body_type_index] * vec2_data_array_stride);
	uint rigid_body_constraint_end_base_address = align_up(rigid_body_constraint_start_base_address + capacities[rigid_body_type_index] * uint_data_array_stride);
	uint rigid_body_read_position_flags_base_address = align_up(rigid_body_constraint_end_base_address + capacities[rigid_body_type_index] * uint_data_array_stride);
	uint rigid_body_read_velocity_flags_base_address = align_up(rigid_body_read_position_flags_base_address + capacities[rigid_body_type_index] * uvec4_data_array_stride);
	uint rigid_body_write_position_flags_base_address = align_up(rigid_body_read_velocity_flags_base_address + capacities[rigid_body_type_index] * uvec4_data_array_stride);
	uint rigid_body_write_velocity_flags_base_address = align_up(rigid_body_write_position_flags_base_address + capacities[rigid_body_type_index] * uvec4_data_array_stride);

	uint rigid_body_inverse_mass_inertia_base = address_to_vec2_index(rigid_body_inverse_mass_inertia_base_address);
	uint rigid_body_constraint_start_base = address_to_uint_index(rigid_body_constraint_start_base_address);
	uint rigid_body_constraint_end_base = address_to_uint_index(rigid_body_constraint_end_base_address);
	uint rigid_body_read_position_flags_base = address_to_uvec4_index(rigid_body_read_position_flags_base_address);
	uint rigid_body_read_velocity_flags_base = address_to_uvec4_index(rigid_body_read_velocity_flags_base_address);
	uint rigid_body_write_position_flags_base = address_to_uvec4_index(rigid_body_write_position_flags_base_address);
	uint rigid_body_write_velocity_flags_base = address_to_uvec4_index(rigid_body_write_velocity_flags_base_address);

	fixed_data.rigid_body_inverse_mass_inertia_base = rigid_body_inverse_mass_inertia_base;
	fixed_data.rigid_body_constraint_start_base = rigid_body_constraint_start_base;
	fixed_data.rigid_body_constraint_end_base = rigid_body_constraint_end_base;
	fixed_data.rigid_body_read_position_flags_base = rigid_body_read_position_flags_base;
	fixed_data.rigid_body_read_velocity_flags_base = rigid_body_read_velocity_flags_base;
	fixed_data.rigid_body_write_position_flags_base = rigid_body_write_position_flags_base;
	fixed_data.rigid_body_write_velocity_flags_base = rigid_body_write_velocity_flags_base;

	capacities[rigid_body_triangle_type_index] = capacities[rigid_body_type_index];
	
	uint rigid_body_triangle_body_base_address = align_up(rigid_body_write_velocity_flags_base_address + capacities[rigid_body_type_index] * uvec4_data_array_stride);
	uint rigid_body_triangle_vertex_base_address = align_up(rigid_body_triangle_body_base_address + capacities[rigid_body_triangle_type_index] * uint_data_array_stride);

	uint rigid_body_triangle_body_base = address_to_uint_index(rigid_body_triangle_body_base_address);
	uint rigid_body_triangle_vertex_base = address_to_vec2_index(rigid_body_triangle_vertex_base_address);

	fixed_data.rigid_body_triangle_body_base = rigid_body_triangle_body_base;
	fixed_data.rigid_body_triangle_vertex_base = rigid_body_triangle_vertex_base;

	capacities[rigid_body_circle_type_index] = capacities[rigid_body_type_index];

	uint leaf_bounding_box_capacity = 0u;
	uint next_bounding_box_local_base = 0u;
	uint leaf_bounding_box_local_bases[leaf_bounding_box_type_count];

	next_bounding_box_local_base = align_up_to_common_base(next_bounding_box_local_base);
	leaf_bounding_box_local_bases[rigid_body_circle_bounding_box_type] = next_bounding_box_local_base;

	uint rigid_body_circle_body_position_radius_base_address = align_up(rigid_body_triangle_vertex_base_address + capacities[rigid_body_triangle_type_index] * 3u * vec2_data_array_stride);

	uint rigid_body_circle_body_position_radius_base = address_to_uvec4_index(rigid_body_circle_body_position_radius_base_address);

	fixed_data.rigid_body_circle_body_position_radius_base = rigid_body_circle_body_position_radius_base;

	leaf_bounding_box_capacity += capacities[rigid_body_circle_type_index];
	next_bounding_box_local_base += capacities[rigid_body_circle_type_index];

	uint inner_bounding_box_capacity = leaf_bounding_box_capacity - 1u;
	
	uint leaf_bounding_box_parent_base_address = align_up(rigid_body_circle_body_position_radius_base_address + capacities[rigid_body_circle_type_index] * uvec4_data_array_stride);
	uint leaf_bounding_box_parent_base = address_to_uint_index(leaf_bounding_box_parent_base_address);

	uint inner_bounding_box_child_pair_base_address = align_up(leaf_bounding_box_parent_base_address + next_bounding_box_local_base * uint_data_array_stride);
	uint inner_bounding_box_child_pair_base = address_to_uvec2_index(inner_bounding_box_child_pair_base_address);
	fixed_data.inner_bounding_box_child_pair_base = inner_bounding_box_child_pair_base;

	uint read_bounding_box_base_address = align_up(inner_bounding_box_child_pair_base_address + inner_bounding_box_capacity * uvec2_data_array_stride);
	uint read_bounding_box_base = address_to_uvec4_index(read_bounding_box_base_address);
	uint read_inner_bounding_box_base_address = align_up(read_bounding_box_base_address + next_bounding_box_local_base * uvec4_data_array_stride);
	fixed_data.read_inner_bounding_box_base = address_to_uvec4_index(read_inner_bounding_box_base_address);

	uint write_bounding_box_base_address = align_up(read_inner_bounding_box_base_address + inner_bounding_box_capacity * uvec4_data_array_stride);
	uint write_bounding_box_base = address_to_uvec4_index(write_bounding_box_base_address);
	uint write_inner_bounding_box_base_address = align_up(write_bounding_box_base_address + next_bounding_box_local_base * uvec4_data_array_stride);
	fixed_data.write_inner_bounding_box_base = address_to_uvec4_index(write_inner_bounding_box_base_address);

	for (uint leaf_bounding_box_type = 0u; leaf_bounding_box_type < leaf_bounding_box_type_count; ++leaf_bounding_box_type)
	{
		uint local_base = leaf_bounding_box_local_bases[leaf_bounding_box_type];

		fixed_data.leaf_bounding_box_parent_bases[leaf_bounding_box_type] = leaf_bounding_box_parent_base + local_base;
		fixed_data.read_leaf_bounding_box_bases[leaf_bounding_box_type] = read_bounding_box_base + local_base;
		fixed_data.write_leaf_bounding_box_bases[leaf_bounding_box_type] = write_bounding_box_base + local_base;
	}

	uint rigid_body_circle_contact_constraint_spawner_count = capacities[rigid_body_circle_type_index] * (capacities[rigid_body_circle_type_index] - 1u) / 2u;
	
	const uint rigid_body_circle_contact_constraint_spawner_capacity_factor = 1u;
	capacities[rigid_body_circle_contact_constraint_spawner_type_index] =
		rigid_body_circle_contact_constraint_spawner_capacity_factor *
		rigid_body_circle_contact_constraint_spawner_count;

	uint rigid_body_circle_contact_constraint_spawner_indices_flags_base_address = align_up(write_inner_bounding_box_base_address + inner_bounding_box_capacity * uvec4_data_array_stride);
	old_death_index_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index] = align_up(rigid_body_circle_contact_constraint_spawner_indices_flags_base_address + capacities[rigid_body_circle_contact_constraint_spawner_type_index] * uvec4_data_array_stride);
	old_killed_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index] = align_up(old_death_index_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index] + capacities[rigid_body_circle_contact_constraint_spawner_type_index] * uint_data_array_stride);
	death_index_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index] = align_up(old_killed_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index] + capacities[rigid_body_circle_contact_constraint_spawner_type_index] * uint_data_array_stride);
	killed_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index] = align_up(death_index_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index] + capacities[rigid_body_circle_contact_constraint_spawner_type_index] * uint_data_array_stride);

	uint rigid_body_circle_contact_constraint_spawner_indices_flags_base = address_to_uvec4_index(rigid_body_circle_contact_constraint_spawner_indices_flags_base_address);
	old_death_index_bases[rigid_body_circle_contact_constraint_spawner_type_index] = address_to_uint_index(old_death_index_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index]);
	old_killed_bases[rigid_body_circle_contact_constraint_spawner_type_index] = address_to_uint_index(old_killed_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index]);
	death_index_bases[rigid_body_circle_contact_constraint_spawner_type_index] = address_to_uint_index(death_index_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index]);
	killed_bases[rigid_body_circle_contact_constraint_spawner_type_index] = address_to_uint_index(killed_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index]);

	fixed_data.rigid_body_circle_contact_constraint_spawner_indices_flags_base = rigid_body_circle_contact_constraint_spawner_indices_flags_base;

	capacities[point_mass_distance_constraint_type_index] = columns * (rows - 1u) + rows * (columns - 1u);

	uint point_mass_distance_constraint_flags_target_distance_base_address = align_up(killed_base_addresses[rigid_body_circle_contact_constraint_spawner_type_index] + capacities[rigid_body_circle_contact_constraint_spawner_type_index] * uint_data_array_stride);
	uint point_mass_distance_constraint_indices_turns_base_address = align_up(point_mass_distance_constraint_flags_target_distance_base_address + capacities[point_mass_distance_constraint_type_index] * uvec2_data_array_stride);
	uint point_mass_distance_constraint_delta_position_velocity_base_address = align_up(point_mass_distance_constraint_indices_turns_base_address + capacities[point_mass_distance_constraint_type_index] * uvec4_data_array_stride);

	uint point_mass_distance_constraint_flags_target_distance_base = address_to_uvec2_index(point_mass_distance_constraint_flags_target_distance_base_address);
	uint point_mass_distance_constraint_indices_turns_base = address_to_uvec4_index(point_mass_distance_constraint_indices_turns_base_address);
	uint point_mass_distance_constraint_delta_position_velocity_base = address_to_uvec4_index(point_mass_distance_constraint_delta_position_velocity_base_address);

	fixed_data.point_mass_distance_constraint_flags_target_distance_base = point_mass_distance_constraint_flags_target_distance_base;
	fixed_data.point_mass_distance_constraint_indices_turns_base = point_mass_distance_constraint_indices_turns_base;
	fixed_data.point_mass_distance_constraint_delta_position_velocity_base = point_mass_distance_constraint_delta_position_velocity_base;

	capacities[rigid_body_circle_contact_constraint_type_index] = capacities[rigid_body_circle_contact_constraint_spawner_type_index];
	
	uint rigid_body_circle_contact_constraint_flags_base_address = align_up(point_mass_distance_constraint_delta_position_velocity_base_address + capacities[point_mass_distance_constraint_type_index] * uvec4_data_array_stride);
	uint rigid_body_circle_contact_constraint_indices_turns_base_address = align_up(rigid_body_circle_contact_constraint_flags_base_address + capacities[rigid_body_circle_contact_constraint_type_index] * uint_data_array_stride);
	uint rigid_body_circle_contact_constraint_impulse_base_address = align_up(rigid_body_circle_contact_constraint_indices_turns_base_address + capacities[rigid_body_circle_contact_constraint_type_index] * uvec4_data_array_stride);
	old_death_index_base_addresses[rigid_body_circle_contact_constraint_type_index] = align_up(rigid_body_circle_contact_constraint_impulse_base_address + capacities[rigid_body_circle_contact_constraint_type_index] * uvec4_data_array_stride);
	old_killed_base_addresses[rigid_body_circle_contact_constraint_type_index] = align_up(old_death_index_base_addresses[rigid_body_circle_contact_constraint_type_index] + capacities[rigid_body_circle_contact_constraint_type_index] * uint_data_array_stride);
	death_index_base_addresses[rigid_body_circle_contact_constraint_type_index] = align_up(old_killed_base_addresses[rigid_body_circle_contact_constraint_type_index] + capacities[rigid_body_circle_contact_constraint_type_index] * uint_data_array_stride);
	killed_base_addresses[rigid_body_circle_contact_constraint_type_index] = align_up(death_index_base_addresses[rigid_body_circle_contact_constraint_type_index] + capacities[rigid_body_circle_contact_constraint_type_index] * uint_data_array_stride);

	uint rigid_body_circle_contact_constraint_flags_base = address_to_uint_index(rigid_body_circle_contact_constraint_flags_base_address);
	uint rigid_body_circle_contact_constraint_indices_turns_base = address_to_uvec4_index(rigid_body_circle_contact_constraint_indices_turns_base_address);
	uint rigid_body_circle_contact_constraint_impulse_base = address_to_vec4_index(rigid_body_circle_contact_constraint_impulse_base_address);
	old_death_index_bases[rigid_body_circle_contact_constraint_type_index] = address_to_uint_index(old_death_index_base_addresses[rigid_body_circle_contact_constraint_type_index]);
	old_killed_bases[rigid_body_circle_contact_constraint_type_index] = address_to_uint_index(old_killed_base_addresses[rigid_body_circle_contact_constraint_type_index]);
	death_index_bases[rigid_body_circle_contact_constraint_type_index] = address_to_uint_index(death_index_base_addresses[rigid_body_circle_contact_constraint_type_index]);
	killed_bases[rigid_body_circle_contact_constraint_type_index] = address_to_uint_index(killed_base_addresses[rigid_body_circle_contact_constraint_type_index]);

	fixed_data.rigid_body_circle_contact_constraint_flags_base = rigid_body_circle_contact_constraint_flags_base;
	fixed_data.rigid_body_circle_contact_constraint_indices_turns_base = rigid_body_circle_contact_constraint_indices_turns_base;
	fixed_data.rigid_body_circle_contact_constraint_impulse_base = rigid_body_circle_contact_constraint_impulse_base;

	for (uint entity_type = 0u; entity_type < entity_type_count; ++entity_type)
	{
		fixed_data.capacities[entity_type] = capacities[entity_type];

		fixed_data.old_old_kill_counts[entity_type] = 0u;
		
		fixed_data.old_death_index_bases[entity_type] = old_death_index_bases[entity_type];
		fixed_data.old_killed_bases[entity_type] = old_killed_bases[entity_type];
		fixed_data.old_kill_counts[entity_type] = 0u;

		fixed_data.death_index_bases[entity_type] = death_index_bases[entity_type];
		fixed_data.killed_bases[entity_type] = killed_bases[entity_type];
		fixed_data.kill_counts[entity_type] = 0u;
		//fixed_data.kill_bases[entity_type] = 0u;
		//fixed_data.kill_ends[entity_type] = 0u;
	}

	uint end_base_address = killed_base_addresses[rigid_body_circle_contact_constraint_type_index] + capacities[rigid_body_circle_contact_constraint_type_index] * uint_data_array_stride;
	uint end_base = address_to_uint_index(end_base_address);
	uint has_enough_memory = uint(end_base <= uint_data.data.length());
	
	uint point_mass_count = capacities[point_mass_type_index];//capacities[point_mass_type_index];
	uint rigid_body_count = capacities[rigid_body_type_index];//capacities[rigid_body_type_index];
	uint rigid_body_triangle_count = capacities[rigid_body_triangle_type_index] * 0u;//capacities[rigid_body_triangle_type_index] * 0u;
	uint rigid_body_circle_count = capacities[rigid_body_circle_type_index];//capacities[rigid_body_circle_type_index];
	//uint rigid_body_circle_contact_constraint_spawner_count = capacities[rigid_body_circle_contact_constraint_spawner_type_index];//rigid_body_circle_contact_constraint_spawner_capacity;
	uint point_mass_distance_constraint_count = capacities[point_mass_distance_constraint_type_index];//capacities[point_mass_distance_constraint_type_index];
	uint rigid_body_circle_contact_constraint_count = 0u;

	point_mass_count *= has_enough_memory;
	rigid_body_count *= has_enough_memory;
	rigid_body_triangle_count *= has_enough_memory;
	rigid_body_circle_count *= has_enough_memory;
	rigid_body_circle_contact_constraint_spawner_count *= has_enough_memory;
	point_mass_distance_constraint_count *= has_enough_memory;
	rigid_body_circle_contact_constraint_count *= has_enough_memory;
	rows *= has_enough_memory;
	columns *= has_enough_memory;

	fixed_data.read_counts[point_mass_type_index] = point_mass_count;
	fixed_data.write_counts[point_mass_type_index] = point_mass_count;

	fixed_data.read_counts[rigid_body_type_index] = rigid_body_count;
	fixed_data.write_counts[rigid_body_type_index] = rigid_body_count;

	fixed_data.read_counts[rigid_body_triangle_type_index] = rigid_body_triangle_count;
	fixed_data.write_counts[rigid_body_triangle_type_index] = rigid_body_triangle_count;

	fixed_data.read_counts[rigid_body_circle_type_index] = rigid_body_circle_count;
	fixed_data.write_counts[rigid_body_circle_type_index] = rigid_body_circle_count;

	fixed_data.read_counts[rigid_body_circle_contact_constraint_spawner_type_index] = rigid_body_circle_contact_constraint_spawner_count;
	fixed_data.write_counts[rigid_body_circle_contact_constraint_spawner_type_index] = rigid_body_circle_contact_constraint_spawner_count;

	fixed_data.read_counts[point_mass_distance_constraint_type_index] = point_mass_distance_constraint_count;
	fixed_data.write_counts[point_mass_distance_constraint_type_index] = point_mass_distance_constraint_count;

	fixed_data.read_counts[rigid_body_circle_contact_constraint_type_index] = rigid_body_circle_contact_constraint_count;
	fixed_data.write_counts[rigid_body_circle_contact_constraint_type_index] = rigid_body_circle_contact_constraint_count;

	for (uint dispatch_program_index = 0u; dispatch_program_index < dispatch_program_count; ++dispatch_program_index)
	{
		fixed_data.dispatch_command_flags[dispatch_program_index] = dispatch_command_enabled_mask;

		commands.dispatch_commands[dispatch_program_index].work_group_count_x = 0u;
		commands.dispatch_commands[dispatch_program_index].work_group_count_y = 1u;
		commands.dispatch_commands[dispatch_program_index].work_group_count_z = 1u;
		commands.dispatch_commands[dispatch_program_index].pad = 0u;
	}

	for (uint draw_arrays_program_index = 0u; draw_arrays_program_index < draw_arrays_program_count; ++draw_arrays_program_index)
	{
		fixed_data.draw_arrays_command_flags[draw_arrays_program_index] = draw_arrays_command_enabled_mask;

		commands.draw_arrays_commands[draw_arrays_program_index].count = 0u;
		commands.draw_arrays_commands[draw_arrays_program_index].instance_count = 1u;
		commands.draw_arrays_commands[draw_arrays_program_index].first = 0u;
		commands.draw_arrays_commands[draw_arrays_program_index].base_instance = 0u;
	}

	// TODO: Initialize key state.

	for (uint row = 0u; row < rows; ++row)
	{
		for (uint column = 0u; column < columns; ++column)
		{
			uint point_mass_index = row * columns + column;

			float_data.data[point_mass_inverse_mass_base + point_mass_index] = 1.0;
			uint_data.data[point_mass_constraint_start_base + point_mass_index] = 0u;
			uint_data.data[point_mass_constraint_end_base + point_mass_index] = 0u;
			uint_data.data[point_mass_read_flags_base + point_mass_index] = 0u;
			uvec4_data.data[point_mass_read_position_velocity_base + point_mass_index] = uvec4(0u);
			uint_data.data[point_mass_write_flags_base + point_mass_index] = 0u;
			uvec4_data.data[point_mass_write_position_velocity_base + point_mass_index] = uvec4(ivec4(
				column * distance, -row * distance, 
				0.0 * meters_per_second_in_length_units_per_time_unit, 0.0 * meters_per_second_in_length_units_per_time_unit
			));
		}
	}

	for (uint column = 0u; column < columns; ++column)
	{
		if (column != 0u && column != columns - 1u)
		{
			//continue;
		}
		float_data.data[point_mass_inverse_mass_base + column] = 0.0;
	}

	for (uint rigid_body_index = 0u; rigid_body_index < rigid_body_count; ++rigid_body_index)
	{
		vec2_data.data[rigid_body_inverse_mass_inertia_base + rigid_body_index] = vec2(0.5, 1.0);
		uint_data.data[rigid_body_constraint_start_base + rigid_body_index] = 0u;
		uint_data.data[rigid_body_constraint_end_base + rigid_body_index] = 0u;
		uvec4_data.data[rigid_body_read_position_flags_base + rigid_body_index] = uvec4(0u);
		uvec4_data.data[rigid_body_read_velocity_flags_base + rigid_body_index] = uvec4(0u);
		const uint rigid_body_columns = 10u;
		uvec4_data.data[rigid_body_write_position_flags_base + rigid_body_index] = uvec4
		(
			ivec4
			(
				4.0 * (rigid_body_index % rigid_body_columns) * meter_in_length_units,
				(3.0 + float(rigid_body_index / rigid_body_columns) + 0.1 * float(rigid_body_index)) * meter_in_length_units,
				0.0 * float(rigid_body_index) * radian_in_angle_units,
				0
			)
		);
		uvec4_data.data[rigid_body_write_velocity_flags_base + rigid_body_index] = uvec4
		(
			ivec4
			(
				float(1 - 2 * int(rigid_body_index & 1)) * 1.0 * meters_per_second_in_length_units_per_time_unit, 0.0 * meters_per_second_in_length_units_per_time_unit,
				0.0 * radians_per_second_in_angle_units_per_time_unit, 0u
			)
		);
	}

	for (uint rigid_body_triangle_index = 0u; rigid_body_triangle_index < rigid_body_triangle_count; ++rigid_body_triangle_index)
	{
		uint_data.data[rigid_body_triangle_body_base + rigid_body_triangle_index] = rigid_body_triangle_index;
		uint vertex_index = rigid_body_triangle_vertex_base + rigid_body_triangle_index * 3u;
		const float radius = 0.5;
		vec2_data.data[vertex_index] = radius * vec2(0.0, 1.0);
		const float base_x_offset = 0.5 * sqrt(3.0);
		vec2_data.data[vertex_index + 1u] = radius * vec2(-base_x_offset, -0.5);
		vec2_data.data[vertex_index + 2u] = radius * vec2(base_x_offset, -0.5);
	}

	for (uint rigid_body_circle_index = 0u; rigid_body_circle_index < rigid_body_circle_count; ++rigid_body_circle_index)
	{
		uvec4_data.data[rigid_body_circle_body_position_radius_base + rigid_body_circle_index] = uvec4
		(
			rigid_body_circle_index,
			floatBitsToUint(vec3(0.0, 0.0, 0.5))
		);
	}

	uint rigid_body_circle_contact_constraint_spawner_index = 0u;
	for (uint rigid_body_circle_index_0 = 0u; rigid_body_circle_index_0 < rigid_body_circle_count - 1u; ++rigid_body_circle_index_0)
	{
		for (uint rigid_body_circle_index_1 = rigid_body_circle_index_0 + 1u; rigid_body_circle_index_1 < rigid_body_circle_count; ++rigid_body_circle_index_1)
		{
			uvec4_data.data[rigid_body_circle_contact_constraint_spawner_indices_flags_base + rigid_body_circle_contact_constraint_spawner_index] =
				uvec4(rigid_body_circle_index_0, rigid_body_circle_index_1, 0u, 0u);

			++rigid_body_circle_contact_constraint_spawner_index;
		}
	}

	uint point_mass_distance_constraint_base_index = 0u;

	for (uint column = 0u; column < columns; ++column)
	{
		for (uint row = 0u; row < rows - 1u; ++row)
		{
			uint point_mass_distance_constraint_index = point_mass_distance_constraint_base_index + column * (rows - 1u) + row;

			uint index_0 = row * columns + column;
			uint index_1 = index_0 + columns;

			uvec2_data.data[point_mass_distance_constraint_flags_target_distance_base + point_mass_distance_constraint_index] = uvec2(0u, distance);

			// TODO: Atomic adds
			uint turn_0 = uint_data.data[point_mass_constraint_start_base + index_0];
			turn_0 += uint(-1);
			uint_data.data[point_mass_constraint_start_base + index_0] = turn_0;

			uint turn_1 = uint_data.data[point_mass_constraint_start_base + index_1];
			turn_1 += uint(-1);
			uint_data.data[point_mass_constraint_start_base + index_1] = turn_1;
			
			uvec4_data.data[point_mass_distance_constraint_indices_turns_base + point_mass_distance_constraint_index] = uvec4(index_0, index_1, turn_0, turn_1);
			uvec4_data.data[point_mass_distance_constraint_delta_position_velocity_base + point_mass_distance_constraint_index] = uvec4(0u);
		}
	}
	
	point_mass_distance_constraint_base_index += (columns - 1u) * (rows - 1u) + (rows - 2u) + 1u;

	for (uint row = 0u; row < rows; ++row)
	{
		for (uint column = 0u; column < columns - 1u; ++column)
		{
			uint point_mass_distance_constraint_index = point_mass_distance_constraint_base_index + row * (columns - 1u) + column;

			uint index_0 = row * columns + column;
			uint index_1 = index_0 + 1u;

			uvec2_data.data[point_mass_distance_constraint_flags_target_distance_base + point_mass_distance_constraint_index] = uvec2(0u, distance);

			// TODO: Atomic adds
			uint turn_0 = uint_data.data[point_mass_constraint_start_base + index_0];
			turn_0 += uint(-1);
			uint_data.data[point_mass_constraint_start_base + index_0] = turn_0;

			uint turn_1 = uint_data.data[point_mass_constraint_start_base + index_1];
			turn_1 += uint(-1);	
			uint_data.data[point_mass_constraint_start_base + index_1] = turn_1;
			
			uvec4_data.data[point_mass_distance_constraint_indices_turns_base + point_mass_distance_constraint_index] = uvec4(index_0, index_1, turn_0, turn_1);
			uvec4_data.data[point_mass_distance_constraint_delta_position_velocity_base + point_mass_distance_constraint_index] = uvec4(0u);
		}
	}

	uint last_point_mass_index = point_mass_count - 1u;
	uvec4_data.data[point_mass_write_position_velocity_base + last_point_mass_index].zw = uvec2(ivec2(
		1000.0 * meters_per_second_in_length_units_per_time_unit, 0.0 * meters_per_second_in_length_units_per_time_unit
	));
	float_data.data[point_mass_inverse_mass_base + last_point_mass_index] = 1.0;

	for (uint entity_type = 0u; entity_type < entity_type_count; ++entity_type)
	{
		if (entity_type != rigid_body_circle_contact_constraint_spawner_type_index && entity_type != rigid_body_circle_contact_constraint_type_index)
		{
			continue;
		}

		uint old_death_index_base = old_death_index_bases[entity_type];
		uint death_index_base = death_index_bases[entity_type];
		for (uint index = 0u; index < capacities[entity_type]; ++index)
		{
			uint_data.data[old_death_index_base + index] = null_uint;
			uint_data.data[death_index_base + index] = null_uint;
		}
	}
}
