#pragma once
#include "DEFAULT_COMPUTE_SHADER_LOCAL_SIZE.h"

#define game_logic__util__rigid_body_SOLVE_CONTACT_VELOCITIES_LOCAL_SIZE(environment) \
	game_logic__util__rigid_body_DEFAULT_COMPUTE_SHADER_LOCAL_SIZE(environment)
