layout(local_size_x = 1u) in;
void main()
{
	uint index = gl_GlobalInvocationID.x;
	if (index != 0u)
	{
		return;
	}

	uint height_delimiters_base = fixed_data.inner_bounding_box_height_delimiters_base;

	fixed_data.current_inner_bounding_box_height = 0u;
	fixed_data.current_inner_bounding_box_height_start = 0u;
	fixed_data.current_inner_bounding_box_height_count = uint_data.delimiters[height_delimiters_base];
}
