layout(local_size_x = perform_rigid_body_circle_contact_constraint_spawner_compaction_local_size) in;
void main()
{
	uint killed;
	uint source;

	PRE_TICK_ENTITIES_PERFORM_COMPACTION_DETERMINE_FLOW(rigid_body_circle_contact_constraint_spawner_type_index, killed, source);

	// Copy source -> killed.
	uint indices_flags_base = fixed_data.rigid_body_circle_contact_constraint_spawner_indices_flags_base;
	
	uvec4_data.data[indices_flags_base + killed] = uvec4_data.data[indices_flags_base + source];
}
