layout(local_size_x = initialize_bounding_box_contact_detectors_local_size) in;
void main()
{
	uint index = gl_GlobalInvocationID.x;
	uint count = fixed_data.read_counts[inner_bounding_box_type];
	if (index >= count)
	{
		return;
	}

	uint inner_bounding_box_parent_children_height_base = fixed_data.inner_bounding_box_parent_children_height_base;
	uint indices_source_flags_base = fixed_data.bounding_box_contact_detector_indices_source_flags_base;

	uint inner_bounding_box_parent_children_height_index = inner_bounding_box_parent_children_height_base + index;
	uint indices_source_flags_index = indices_source_flags_base + index;

	uvec4 inner_bounding_box_parent_children_height = uvec4_data.data[inner_bounding_box_parent_children_height_index];
	uvec4_data.data[indices_source_flags_index] = uvec4(inner_bounding_box_parent_children_height.yz, null_uint, 0u);
}
